# Generated by Django 4.1.3 on 2022-12-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoactor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='videodirector',
            options={'verbose_name': 'Режисёр', 'verbose_name_plural': 'Режисёры'},
        ),
    ]
