# Generated by Django 4.1.3 on 2022-12-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_alter_videoactor_options_alter_videodirector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocountrу',
            name='CountryName',
            field=models.CharField(default='США', max_length=100, verbose_name='Название страны'),
            preserve_default=False,
        ),
    ]
