# Generated by Django 4.1.3 on 2022-12-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0003_videocountrу_countryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='Countrу',
            field=models.ManyToManyField(to='mySite.videocountrу', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Types',
            field=models.ManyToManyField(to='mySite.videotype', verbose_name='Жанры'),
        ),
    ]
